name: McPete
version: 1.0
main: org.poiesis.mcpete.PluginMain
author: Nathan
description: My awesome plugin!
commands:
  genCommand:
    description: Make GPT-3.5 generate and execute a command for you
    usage: /genCommand <input...>